# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/FPGA_Code/7020_AD936X_SDR/AD936X_PL/projects/fmcomms2/zc702/zc702.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
# IP: The module: 'system_sys_ps7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA_Code/7020_AD936X_SDR/AD936X_PL/projects/fmcomms2/zc702/zc702.gen/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_ps7_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: F:/FPGA_Code/7020_AD936X_SDR/AD936X_PL/projects/fmcomms2/zc702/zc702.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xci
# IP: The module: 'system_sys_ps7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA_Code/7020_AD936X_SDR/AD936X_PL/projects/fmcomms2/zc702/zc702.gen/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_sys_ps7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
