set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_p]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_n]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_p]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_n]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[0]}]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[0]}]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[1]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[1]}]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[2]}]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[2]}]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[3]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[3]}]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[4]}]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[4]}]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_p[5]}]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_n[5]}]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVDS_25} [get_ports tx_clk_out_p]
set_property -dict {PACKAGE_PIN U15 IOSTANDARD LVDS_25} [get_ports tx_clk_out_n]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVDS_25} [get_ports tx_frame_out_p]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVDS_25} [get_ports tx_frame_out_n]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[0]}]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[0]}]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[1]}]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[1]}]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[2]}]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[2]}]
set_property -dict {PACKAGE_PIN T12 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[3]}]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[3]}]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[4]}]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[4]}]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVDS_25} [get_ports {tx_data_out_p[5]}]
set_property -dict {PACKAGE_PIN V13 IOSTANDARD LVDS_25} [get_ports {tx_data_out_n[5]}]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS25} [get_ports {gpio_status[0]}]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD LVCMOS25} [get_ports {gpio_status[1]}]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS25} [get_ports {gpio_status[2]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS25} [get_ports {gpio_status[3]}]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS25} [get_ports {gpio_status[4]}]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS25} [get_ports {gpio_status[5]}]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS25} [get_ports {gpio_status[6]}]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD LVCMOS25} [get_ports {gpio_status[7]}]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl[0]}]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl[1]}]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl[2]}]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl[3]}]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS25} [get_ports gpio_en_agc]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS25} [get_ports gpio_sync]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS25} [get_ports gpio_resetb]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS25} [get_ports enable]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS25} [get_ports txnrx]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS25} [get_ports spi_clk]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS25} [get_ports spi_mosi]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS25} [get_ports spi_miso]

# constraints
# ad9361



set_property PACKAGE_PIN R17 [get_ports spi_csn]
set_property IOSTANDARD LVCMOS25 [get_ports spi_csn]
set_property PULLTYPE PULLUP [get_ports spi_csn]

# clocks

create_clock -period 4.000 -name rx_clk [get_ports rx_clk_in_p]


set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets i_system_wrapper/system_i/axi_ad9361/inst/i_dev_if/i_clk/clk_ibuf_s]


set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

set_operating_conditions -grade extended
set_load 5.000 [all_outputs]
set_property LOAD 5 [get_ports {ddr_addr[0]}]
set_property LOAD 5 [get_ports {ddr_addr[10]}]
set_property LOAD 5 [get_ports {ddr_addr[11]}]
set_property LOAD 5 [get_ports {ddr_addr[12]}]
set_property LOAD 5 [get_ports {ddr_addr[13]}]
set_property LOAD 5 [get_ports {ddr_addr[14]}]
set_property LOAD 5 [get_ports {ddr_addr[1]}]
set_property LOAD 5 [get_ports {ddr_addr[2]}]
set_property LOAD 5 [get_ports {ddr_addr[3]}]
set_property LOAD 5 [get_ports {ddr_addr[4]}]
set_property LOAD 5 [get_ports {ddr_addr[5]}]
set_property LOAD 5 [get_ports {ddr_addr[6]}]
set_property LOAD 5 [get_ports {ddr_addr[7]}]
set_property LOAD 5 [get_ports {ddr_addr[8]}]
set_property LOAD 5 [get_ports {ddr_addr[9]}]
set_property LOAD 5 [get_ports {ddr_ba[0]}]
set_property LOAD 5 [get_ports {ddr_ba[1]}]
set_property LOAD 5 [get_ports {ddr_ba[2]}]
set_property LOAD 5 [get_ports ddr_cas_n]
set_property LOAD 5 [get_ports ddr_ck_n]
set_property LOAD 5 [get_ports ddr_ck_p]
set_property LOAD 5 [get_ports ddr_cke]
set_property LOAD 5 [get_ports ddr_cs_n]
set_property LOAD 5 [get_ports {ddr_dm[0]}]
set_property LOAD 5 [get_ports {ddr_dm[1]}]
set_property LOAD 5 [get_ports {ddr_dm[2]}]
set_property LOAD 5 [get_ports {ddr_dm[3]}]
set_property LOAD 5 [get_ports {ddr_dq[0]}]
set_property LOAD 5 [get_ports {ddr_dq[10]}]
set_property LOAD 5 [get_ports {ddr_dq[11]}]
set_property LOAD 5 [get_ports {ddr_dq[12]}]
set_property LOAD 5 [get_ports {ddr_dq[13]}]
set_property LOAD 5 [get_ports {ddr_dq[14]}]
set_property LOAD 5 [get_ports {ddr_dq[15]}]
set_property LOAD 5 [get_ports {ddr_dq[16]}]
set_property LOAD 5 [get_ports {ddr_dq[17]}]
set_property LOAD 5 [get_ports {ddr_dq[18]}]
set_property LOAD 5 [get_ports {ddr_dq[19]}]
set_property LOAD 5 [get_ports {ddr_dq[1]}]
set_property LOAD 5 [get_ports {ddr_dq[20]}]
set_property LOAD 5 [get_ports {ddr_dq[21]}]
set_property LOAD 5 [get_ports {ddr_dq[22]}]
set_property LOAD 5 [get_ports {ddr_dq[23]}]
set_property LOAD 5 [get_ports {ddr_dq[24]}]
set_property LOAD 5 [get_ports {ddr_dq[25]}]
set_property LOAD 5 [get_ports {ddr_dq[26]}]
set_property LOAD 5 [get_ports {ddr_dq[27]}]
set_property LOAD 5 [get_ports {ddr_dq[28]}]
set_property LOAD 5 [get_ports {ddr_dq[29]}]
set_property LOAD 5 [get_ports {ddr_dq[2]}]
set_property LOAD 5 [get_ports {ddr_dq[30]}]
set_property LOAD 5 [get_ports {ddr_dq[31]}]
set_property LOAD 5 [get_ports {ddr_dq[3]}]
set_property LOAD 5 [get_ports {ddr_dq[4]}]
set_property LOAD 5 [get_ports {ddr_dq[5]}]
set_property LOAD 5 [get_ports {ddr_dq[6]}]
set_property LOAD 5 [get_ports {ddr_dq[7]}]
set_property LOAD 5 [get_ports {ddr_dq[8]}]
set_property LOAD 5 [get_ports {ddr_dq[9]}]
set_property LOAD 5 [get_ports {ddr_dqs_n[0]}]
set_property LOAD 5 [get_ports {ddr_dqs_n[1]}]
set_property LOAD 5 [get_ports {ddr_dqs_n[2]}]
set_property LOAD 5 [get_ports {ddr_dqs_n[3]}]
set_property LOAD 5 [get_ports {ddr_dqs_p[0]}]
set_property LOAD 5 [get_ports {ddr_dqs_p[1]}]
set_property LOAD 5 [get_ports {ddr_dqs_p[2]}]
set_property LOAD 5 [get_ports {ddr_dqs_p[3]}]
set_property LOAD 5 [get_ports ddr_odt]
set_property LOAD 5 [get_ports ddr_ras_n]
set_property LOAD 5 [get_ports ddr_reset_n]
set_property LOAD 5 [get_ports ddr_we_n]
set_property LOAD 5 [get_ports enable]
set_property LOAD 5 [get_ports fixed_io_ddr_vrn]
set_property LOAD 5 [get_ports fixed_io_ddr_vrp]
set_property LOAD 5 [get_ports {fixed_io_mio[0]}]
set_property LOAD 5 [get_ports {fixed_io_mio[10]}]
set_property LOAD 5 [get_ports {fixed_io_mio[11]}]
set_property LOAD 5 [get_ports {fixed_io_mio[12]}]
set_property LOAD 5 [get_ports {fixed_io_mio[13]}]
set_property LOAD 5 [get_ports {fixed_io_mio[14]}]
set_property LOAD 5 [get_ports {fixed_io_mio[15]}]
set_property LOAD 5 [get_ports {fixed_io_mio[16]}]
set_property LOAD 5 [get_ports {fixed_io_mio[17]}]
set_property LOAD 5 [get_ports {fixed_io_mio[18]}]
set_property LOAD 5 [get_ports {fixed_io_mio[19]}]
set_property LOAD 5 [get_ports {fixed_io_mio[1]}]
set_property LOAD 5 [get_ports {fixed_io_mio[20]}]
set_property LOAD 5 [get_ports {fixed_io_mio[21]}]
set_property LOAD 5 [get_ports {fixed_io_mio[22]}]
set_property LOAD 5 [get_ports {fixed_io_mio[23]}]
set_property LOAD 5 [get_ports {fixed_io_mio[24]}]
set_property LOAD 5 [get_ports {fixed_io_mio[25]}]
set_property LOAD 5 [get_ports {fixed_io_mio[26]}]
set_property LOAD 5 [get_ports {fixed_io_mio[27]}]
set_property LOAD 5 [get_ports {fixed_io_mio[28]}]
set_property LOAD 5 [get_ports {fixed_io_mio[29]}]
set_property LOAD 5 [get_ports {fixed_io_mio[2]}]
set_property LOAD 5 [get_ports {fixed_io_mio[30]}]
set_property LOAD 5 [get_ports {fixed_io_mio[31]}]
set_property LOAD 5 [get_ports {fixed_io_mio[32]}]
set_property LOAD 5 [get_ports {fixed_io_mio[33]}]
set_property LOAD 5 [get_ports {fixed_io_mio[34]}]
set_property LOAD 5 [get_ports {fixed_io_mio[35]}]
set_property LOAD 5 [get_ports {fixed_io_mio[36]}]
set_property LOAD 5 [get_ports {fixed_io_mio[37]}]
set_property LOAD 5 [get_ports {fixed_io_mio[38]}]
set_property LOAD 5 [get_ports {fixed_io_mio[39]}]
set_property LOAD 5 [get_ports {fixed_io_mio[3]}]
set_property LOAD 5 [get_ports {fixed_io_mio[40]}]
set_property LOAD 5 [get_ports {fixed_io_mio[41]}]
set_property LOAD 5 [get_ports {fixed_io_mio[42]}]
set_property LOAD 5 [get_ports {fixed_io_mio[43]}]
set_property LOAD 5 [get_ports {fixed_io_mio[44]}]
set_property LOAD 5 [get_ports {fixed_io_mio[45]}]
set_property LOAD 5 [get_ports {fixed_io_mio[46]}]
set_property LOAD 5 [get_ports {fixed_io_mio[47]}]
set_property LOAD 5 [get_ports {fixed_io_mio[48]}]
set_property LOAD 5 [get_ports {fixed_io_mio[49]}]
set_property LOAD 5 [get_ports {fixed_io_mio[4]}]
set_property LOAD 5 [get_ports {fixed_io_mio[50]}]
set_property LOAD 5 [get_ports {fixed_io_mio[51]}]
set_property LOAD 5 [get_ports {fixed_io_mio[52]}]
set_property LOAD 5 [get_ports {fixed_io_mio[53]}]
set_property LOAD 5 [get_ports {fixed_io_mio[5]}]
set_property LOAD 5 [get_ports {fixed_io_mio[6]}]
set_property LOAD 5 [get_ports {fixed_io_mio[7]}]
set_property LOAD 5 [get_ports {fixed_io_mio[8]}]
set_property LOAD 5 [get_ports {fixed_io_mio[9]}]
set_property LOAD 5 [get_ports fixed_io_ps_clk]
set_property LOAD 5 [get_ports fixed_io_ps_porb]
set_property LOAD 5 [get_ports fixed_io_ps_srstb]
set_property LOAD 5 [get_ports {gpio_ctl[0]}]
set_property LOAD 5 [get_ports {gpio_ctl[1]}]
set_property LOAD 5 [get_ports {gpio_ctl[2]}]
set_property LOAD 5 [get_ports {gpio_ctl[3]}]
set_property LOAD 5 [get_ports gpio_en_agc]
set_property LOAD 5 [get_ports gpio_resetb]
set_property LOAD 5 [get_ports {gpio_status[0]}]
set_property LOAD 5 [get_ports {gpio_status[1]}]
set_property LOAD 5 [get_ports {gpio_status[2]}]
set_property LOAD 5 [get_ports {gpio_status[3]}]
set_property LOAD 5 [get_ports {gpio_status[4]}]
set_property LOAD 5 [get_ports {gpio_status[5]}]
set_property LOAD 5 [get_ports {gpio_status[6]}]
set_property LOAD 5 [get_ports {gpio_status[7]}]
set_property LOAD 5 [get_ports gpio_sync]
set_property LOAD 5 [get_ports spi_clk]
set_property LOAD 5 [get_ports spi_csn]
set_property LOAD 5 [get_ports spi_mosi]
set_property LOAD 5 [get_ports tx_clk_out_n]
set_property LOAD 5 [get_ports tx_clk_out_p]
set_property LOAD 5 [get_ports {tx_data_out_n[0]}]
set_property LOAD 5 [get_ports {tx_data_out_n[1]}]
set_property LOAD 5 [get_ports {tx_data_out_n[2]}]
set_property LOAD 5 [get_ports {tx_data_out_n[3]}]
set_property LOAD 5 [get_ports {tx_data_out_n[4]}]
set_property LOAD 5 [get_ports {tx_data_out_n[5]}]
set_property LOAD 5 [get_ports {tx_data_out_p[0]}]
set_property LOAD 5 [get_ports {tx_data_out_p[1]}]
set_property LOAD 5 [get_ports {tx_data_out_p[2]}]
set_property LOAD 5 [get_ports {tx_data_out_p[3]}]
set_property LOAD 5 [get_ports {tx_data_out_p[4]}]
set_property LOAD 5 [get_ports {tx_data_out_p[5]}]
set_property LOAD 5 [get_ports tx_frame_out_n]
set_property LOAD 5 [get_ports tx_frame_out_p]
set_property LOAD 5 [get_ports txnrx]

set_property MARK_DEBUG true [get_nets {gpio_ctl_IBUF[0]}]
set_property MARK_DEBUG true [get_nets {gpio_ctl_IBUF[1]}]
set_property MARK_DEBUG true [get_nets {gpio_ctl_IBUF[2]}]
set_property MARK_DEBUG true [get_nets {gpio_ctl_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {gpio_ctl_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {gpio_ctl_OBUF[2]}]
